[project]
name = "geo-proy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gggelme", email = "gelmettisantiago@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
]

[project.scripts]
geo-proy = "geo_proy:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
